POST http://localhost:3001/users/create
Content-Type: application/json

{
  "firstname": "Abdullah",
  "lastname": "Mahin",  
  "email": "mahin@gmail.com",
  "password": " Mahin@1234",
  "role": "admin",
  "phone": "01573863968",
  "profileImage": "https://example.com/profile.jpg"
}
